### ISSUE TITLE
project_graph is not adding itself to Path or doesn't really install correctly on windows

### ISSUE THREAD

**Issue by Chaosminecraft** [fior-di-latte/project_graph#1]
i wanted to Visualise what Function tree my Code had and stumbled upon your project and i thought "let's give it a try"

i didn't mind that i had to install GIT, but it didn't work, CMD just gave that error:

C:\Users\Volks\Documents\PYTHON\text converter\Developement\Console version>project_graph -a TextConverter.py
The "project_graph" command is either misspelled or
could not be found.

There is a Screenshot of what i tried:
![Screenshot 2023-07-18 225237](https://github.com/fior-di-latte/project_graph/assets/48801311/67109cc7-8cc4-4d28-9434-e7ab2c95631f)

**Comment by fior-di-latte** [comment]
Hi, Chaosminecraft, thanks for reaching out.
Unfortunately, this project  only supports UNIX-based OS as it is stated in the [blog](https://www.statworx.com/en/content-hub/blog/how-to-automatically-create-project-graphs-with-call-graph/). 
Hence, Windows will not work.
Hope you'll find some other solution that suits your needs elsewhere.

**Comment by Chaosminecraft** [comment]
Okay, shhould it work on Linux Ubuntu?

**Comment by fior-di-latte** [comment]
Yes, it is supposed to work. I tested it on Ubuntu when I wrote it two years ago.
Haven't used the program for quite some time - so I just tested it a minute ago on macOS. Still works! :)
